### ISSUE TITLE
No TTS Sound

### ISSUE THREAD

**Issue by sangoku116** [Minizbot2012/LinuxTTSPlugin#2]
I added the plugin into ACT and when I press the play button next to a trigger it does not output any sound. It also displays an error with the plugin when closing ACT:

![e08f368d09e0490f8df4174f9c3bee0f](https://user-images.githubusercontent.com/18174977/82130036-c5a3f780-9795-11ea-81dc-936033517493.png)

**Comment by valarnin** [comment]
Disable the `Use Pipe` option and restart ACT.

**Comment by sangoku116** [comment]
Disabling the ```Use Pipe``` did work. I also messed around with the argument and decided to use espeak-ng.
